### ISSUE TITLE
add regression functions

### ISSUE THREAD

**Issue by behrenle** [arithmico/arithmico#107]
- [x] linear regression
- [x] quadratic regression
- [x] polynomial regression
- [x] exponential regression
- [x] logistic regression

**Comment by b-g-h** [comment]
für Baden-Württemberg wäre erforderlich:
1. Grades
2. Grades
3. Grades
4. Grades
logarithmisch
Potenziell
Exponentiell

Danke :)


</body>

</html>

**Comment by behrenle** [comment]
Danke für das Feedback wir werden in unserem nächsten Refinement-Termin darüber reden

**Comment by tirextech** [comment]
Hallo,
die Regressionsfunktion(en) werden frühestens im Frühjahr '23 implementiert, da wir derzeit an einer Plotfunktion arbeiten.
MfG

**Comment by tirextech** [comment]
Hallo,
wird multiple lineare und exponentielle, sowie multinomiale logistische Regression benötigt?

HI,
is multiple linear and exponential, or multinomial logistic regression needed?
