### ISSUE TITLE
information about selected element

### ISSUE THREAD

**Issue by cssbue** [arithmico/arithmico#336]
Visually, it is not clear which element within the help is currently active, i.e. which entry would be copied to the clipboard, for example. The same applies, for example, to settings, interface "Copy help text by". It is not recognisable whether the slide switch is focused. The Request is therefore to make it clear by framing or the like on which element one is focussed.

**Comment by cssbue** [comment]
Makes sense, will be adapted.

**Comment by behrenle** [comment]
duplicate, see #439
